<?php
require_once '../config/Database.php';
require_once '../config/auth.php';
requerir_login(['admin_hotel','admin','recepcionista','recepcion']);
$db=(new Database())->connect();$idHotel=(int)id_hotel_actual();
$st=$db->prepare("SELECT nombre_comercial,slug FROM hoteles WHERE id_hotel=? LIMIT 1");$st->execute([$idHotel]);$hotel=$st->fetch(PDO::FETCH_ASSOC)?:[];
$st=$db->prepare("SELECT e.id_encuesta,e.titulo,e.descripcion,e.umbral_publicar,COUNT(a.id_area) total_areas FROM encuestas e LEFT JOIN encuesta_areas a ON a.id_encuesta=e.id_encuesta WHERE e.id_hotel=? AND e.estado='ACTIVA' GROUP BY e.id_encuesta ORDER BY e.id_encuesta DESC");$st->execute([$idHotel]);$encuestas=$st->fetchAll(PDO::FETCH_ASSOC);
$scheme=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http';$host=$_SERVER['HTTP_HOST']??'localhost';$base=rtrim(dirname($_SERVER['SCRIPT_NAME']??''),'/');
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Enlaces de encuestas</title><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"><style>*{box-sizing:border-box}body{margin:0;background:#f4f7fb;color:#152231;font-family:Poppins}.top{background:#162330;color:#fff;padding:16px 24px;display:flex;justify-content:space-between;align-items:center}.top a{background:#fff;color:#162330;padding:10px 14px;border-radius:12px;text-decoration:none;font-weight:800}.wrap{max-width:1000px;margin:28px auto;padding:0 18px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:18px;padding:18px;margin-bottom:13px;box-shadow:0 12px 35px #0f172a0c}.row{display:flex;justify-content:space-between;align-items:center;gap:14px;flex-wrap:wrap}.small{font-size:12px;color:#64748b}.actions{display:flex;gap:9px}.btn{border:0;border-radius:10px;padding:10px 13px;font-weight:800;font-family:Poppins;cursor:pointer;text-decoration:none}.open{background:#2563eb;color:#fff}.copy{background:#ecfdf5;color:#047857}</style></head><body><header class="top"><b><i class="fa-solid fa-link"></i> Enlaces de encuestas · <?=htmlspecialchars($hotel['nombre_comercial']??'Hotel')?></b><a href="recepcion.php">Volver</a></header><main class="wrap"><h1>Encuestas disponibles para enviar</h1><p class="small">El recepcionista puede abrir o copiar estos enlaces para enviarlos a los clientes.</p><?php if(!$encuestas):?><div class="card">No hay encuestas activas.</div><?php endif;?><?php foreach($encuestas as $e):$url=$scheme.'://'.$host.$base.'/encuesta_publica.php?hotel='.rawurlencode($hotel['slug']??'').'&encuesta='.(int)$e['id_encuesta'];?><section class="card"><div class="row"><div><h3 style="margin:0 0 5px"><?=htmlspecialchars($e['titulo'])?></h3><div class="small"><?=(int)$e['total_areas']?> áreas · Enlaces desde <?=number_format((float)$e['umbral_publicar'],0)?> estrellas</div><?php if($e['descripcion']):?><div class="small" style="margin-top:5px"><?=htmlspecialchars($e['descripcion'])?></div><?php endif;?></div><div class="actions"><a class="btn open" href="<?=htmlspecialchars($url)?>" target="_blank"><i class="fa-solid fa-up-right-from-square"></i> Abrir</a><button class="btn copy" onclick='copiar(<?=json_encode($url)?>)'><i class="fa-solid fa-copy"></i> Copiar enlace</button></div></div></section><?php endforeach;?></main><script>function copiar(url){navigator.clipboard.writeText(url).then(()=>alert('Enlace copiado'));}</script></body></html>
