<?php
require_once '../config/Database.php';
require_once '../config/auth.php';
requerir_login(['admin_hotel','admin']);
$db=(new Database())->connect();
$idUsuario=(int)($_SESSION['usuario']['id_usuario']??0);
$idHotel=(int)id_hotel_actual();
$msg='';$tipo='ok';
if($_SERVER['REQUEST_METHOD']==='POST' && ($_POST['accion']??'')==='cambiar_password'){
    $actual=(string)($_POST['password_actual']??'');
    $nueva=(string)($_POST['password_nueva']??'');
    $confirmar=(string)($_POST['password_confirmar']??'');
    $st=$db->prepare("SELECT password_hash FROM usuarios WHERE id_usuario=? AND id_hotel=? LIMIT 1");$st->execute([$idUsuario,$idHotel]);$hash=$st->fetchColumn();
    if(!$hash || !password_verify($actual,$hash)){ $tipo='error';$msg='La contraseña actual no es correcta.'; }
    elseif(strlen($nueva)<6){$tipo='error';$msg='La nueva contraseña debe tener al menos 6 caracteres.';}
    elseif($nueva!==$confirmar){$tipo='error';$msg='Las contraseñas nuevas no coinciden.';}
    else{$up=$db->prepare("UPDATE usuarios SET password_hash=? WHERE id_usuario=? AND id_hotel=?");$up->execute([password_hash($nueva,PASSWORD_DEFAULT),$idUsuario,$idHotel]);$msg='Contraseña actualizada correctamente.';}
}
$st=$db->prepare("SELECT u.usuario,u.email,u.nombres,u.apellidos,u.telefono,u.estado,h.nombre_comercial,h.slug,h.fecha_inicio_plan,h.fecha_fin_plan,h.estado estado_hotel,p.nombre_plan,p.meses FROM usuarios u INNER JOIN hoteles h ON h.id_hotel=u.id_hotel LEFT JOIN planes p ON p.id_plan=h.id_plan WHERE u.id_usuario=? AND u.id_hotel=? LIMIT 1");
$st->execute([$idUsuario,$idHotel]);$d=$st->fetch(PDO::FETCH_ASSOC);
if(!$d){http_response_code(404);exit('Perfil no encontrado.');}
$hoy=new DateTime('today');$vence=new DateTime($d['fecha_fin_plan']);$dias=(int)$hoy->diff($vence)->format('%r%a');
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mi perfil | CRM Hoteles</title><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"><style>
:root{--nav:#162330;--gold:#d4af37;--line:#e2e8f0;--muted:#64748b;--green:#16a06a}*{box-sizing:border-box}body{margin:0;font-family:Poppins;background:linear-gradient(180deg,#eef4fa,#f8fafc);color:#13202b}.top{background:#162330;color:#fff;padding:17px 25px;display:flex;justify-content:space-between;align-items:center}.top a{background:#fff;color:#162330;text-decoration:none;padding:10px 14px;border-radius:12px;font-weight:800}.wrap{max-width:1000px;margin:30px auto;padding:0 18px}.hero h1{margin:0}.hero p{color:var(--muted)}.grid{display:grid;grid-template-columns:1.15fr .85fr;gap:20px}.card{background:#fff;border:1px solid var(--line);border-radius:22px;padding:22px;box-shadow:0 18px 45px #0f172a12}.info{display:grid;grid-template-columns:1fr 1fr;gap:13px}.item{background:#f8fafc;border:1px solid var(--line);border-radius:14px;padding:14px}.item span{display:block;color:var(--muted);font-size:11px;font-weight:800;text-transform:uppercase}.item b{display:block;margin-top:5px}.days{font-size:34px;color:<?= $dias<=15?'#dc2626':'#087344' ?>}.field{margin-bottom:13px}.field label{display:block;font-size:12px;font-weight:800;margin-bottom:6px}.field input{width:100%;padding:12px;border:1px solid #cbd5e1;border-radius:11px;font-family:Poppins}.btn{border:0;background:var(--green);color:#fff;padding:12px 16px;border-radius:12px;font-weight:800;cursor:pointer}.msg{padding:12px 14px;border-radius:12px;margin-bottom:15px}.msg.ok{background:#dcfce7;color:#166534}.msg.error{background:#fee2e2;color:#991b1b}@media(max-width:800px){.grid,.info{grid-template-columns:1fr}}
</style></head><body><header class="top"><b><i class="fa-solid fa-user-circle" style="color:var(--gold)"></i> Mi perfil</b><a href="recepcion.php"><i class="fa-solid fa-arrow-left"></i> Volver</a></header><main class="wrap"><section class="hero"><h1><?=htmlspecialchars($d['nombres'].' '.$d['apellidos'])?></h1><p>Datos de cuenta, plan contratado y seguridad.</p></section><?php if($msg):?><div class="msg <?=$tipo?>"><?=htmlspecialchars($msg)?></div><?php endif;?><div class="grid"><section class="card"><h2>Datos de la cuenta</h2><div class="info"><div class="item"><span>Usuario</span><b><?=htmlspecialchars($d['usuario'])?></b></div><div class="item"><span>Hotel</span><b><?=htmlspecialchars($d['nombre_comercial'])?></b></div><div class="item"><span>Correo</span><b><?=htmlspecialchars($d['email']?:'-')?></b></div><div class="item"><span>Teléfono</span><b><?=htmlspecialchars($d['telefono']?:'-')?></b></div><div class="item"><span>Plan</span><b><?=htmlspecialchars($d['nombre_plan']?:'-')?></b></div><div class="item"><span>Inicio</span><b><?=htmlspecialchars($d['fecha_inicio_plan'])?></b></div><div class="item"><span>Vencimiento</span><b><?=htmlspecialchars($d['fecha_fin_plan'])?></b></div><div class="item"><span>Estado</span><b><?=htmlspecialchars($d['estado_hotel'])?></b></div><div class="item" style="grid-column:1/-1"><span>Tiempo restante</span><b class="days"><?=$dias>=0?$dias.' días':'Vencido hace '.abs($dias).' días'?></b></div></div></section><section class="card"><h2>Cambiar contraseña</h2><form method="post"><input type="hidden" name="accion" value="cambiar_password"><div class="field"><label>Contraseña actual</label><input type="password" name="password_actual" required></div><div class="field"><label>Nueva contraseña</label><input type="password" name="password_nueva" minlength="6" required></div><div class="field"><label>Confirmar nueva contraseña</label><input type="password" name="password_confirmar" minlength="6" required></div><button class="btn"><i class="fa-solid fa-key"></i> Actualizar contraseña</button></form></section></div></main></body></html>
